debug: false

# Admin commands permission: mineshark.admin
min-players: 2

messages:
  join:
    - "&7-----------------------------------"
    - "&aEntraste al mundo &f&lPVP"
    - "&cCuidado, pueden ver jugadores"
    - "&eTendras unos segundos de invulnerabilidad"
    - "&7-----------------------------------"
  safe-actionbar: "&a&lEstas seguro por &f%time !"

game:
  # ran-spawn-loc | Los jugadores aparecen en lugares random si esto esta activo
  ran-spawn-loc: true
  safe-time: 10

spawn: {}

death:
  summon-lightning: true
  player-execute:
    - "home"
  console-execute:
    - "say %p death"