name: MineShark1
version: '${project.version}'
main: org.mineshark.ms1.me.seb.java.MineShark1
authors:
  - SebDev
  - MineShark
author: SebDev
commands:
  minesharkpvp:
    permission: mineshark.admin
    aliases: [mineshark1]

  join:
    aliases: [joinpvp]

  leave:
    aliases: [leavepvp]