name: MineShark1
version: '1.0-SNAPSHOT'
main: org.mineshark.ms1.me.seb.java.MineShark1
authors:
  - SebDev
  - MineShark
author: SebDev
commands:
  minesharkarena:
    permission: mineshark.admin
    aliases: [mineshark1]